# Generated by Django 3.2.5 on 2021-09-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210924_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('classSection', models.CharField(max_length=10)),
                ('rollno', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('bookName', models.ManyToManyField(to='main.Book')),
            ],
        ),
    ]
