# Generated by Django 3.2.5 on 2021-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_issuebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='issued',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
