# Generated by Django 3.2.5 on 2021-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_issuebook_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='issued',
        ),
        migrations.AddField(
            model_name='book',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
