# Generated by Django 3.2.5 on 2021-10-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_issuebook_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='time',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='bookName',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='bookName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.book'),
            preserve_default=False,
        ),
    ]
