# Generated by Django 3.2.5 on 2021-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211001_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='due_date',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
