# Generated by Django 4.0 on 2021-12-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='bookName',
            new_name='book',
        ),
    ]
