# Generated by Django 4.0 on 2022-01-10 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_book_user_alter_issuebook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 10, 7, 39, 22, 551646, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
